### ISSUE TITLE
#<Errno::ECONNREFUSED: Connection refused - connect(2) for "NA.api.pvp.net" port 80>

### ISSUE THREAD

**Issue by jcward10** [mikamai/ruby-lol#37]
First time really working with an api. This gem was working yesterday. I dont know what I did but now its not. Help??

**Comment by jcward10** [comment]
I am on vacation in the mountains and my internet only has a 3 Mbps download. Would that have something to do with it?

**Comment by intinig** [comment]
Pull from master. They moved to ssl. Going to release an updated gem on Monday.

**Comment by jcward10** [comment]
Sweet Thanks !! If you have any more work you want help with, just ping me on here!

**Comment by intinig** [comment]
A gem has been released with support with https.
