### ISSUE TITLE
404 not found for league_entry

### ISSUE THREAD

**Issue by jcward10** [mikamai/ruby-lol#42]
When checking for client.league.get_entries(summoner_id), if the summoner is not ranked yet, the app crashes returning a 404. Can we return nil instead?

**Comment by jcward10** [comment]
>> catch lol.league.get_entries(user.summoner_id)
!! #<Lol::NotFound: 404 Not Found>

**Comment by intinig** [comment]
When we designed the library we made the conscious decision to raise a 404 when the Riot API returns a 404.

The correct way to handle it is, if you know you might be requesting a 404, to rescue the error in your code (that's how we do it :))

**Comment by jcward10** [comment]
Thanks dude !! Still learning I just started ruby last May. This is an awesome gem incase I havent told you yet

**Comment by intinig** [comment]
No problem. Happy you like it :)
