### ISSUE TITLE
UFW firewall

### ISSUE THREAD

**Issue by jcward10** [mikamai/ruby-lol#45]
Hey guys, first off I have been loving the work you have done on this gem. Let me know if there is something I can do to add to it. I have a problem though. When I have my firewall on, I cannot make an api call. But if I disable my firewall, I can make api calls perfectly. Do you have any advice on how to allow lol api calls? Do I need to just whitelist the lol api ip?

**Comment by intinig** [comment]
Thanks for the nice words :)

You should open your firewall so it can make https request to the api endpoints (https://developer.riotgames.com/docs/regional-endpoints)

As far as contributing goes, pick something you think it's missing and send a pull request! (Or write some docs ;)

**Comment by jcward10** [comment]
Thanks man!
