### ISSUE TITLE
MatchHistoryRequest returns Lol::InvalidAPIResponse

### ISSUE THREAD

**Issue by jclif** [mikamai/ruby-lol#49]
I believe the matchhistory endpoint has been deprecated. Would it be possible to deploy a new gem version with the changes in master (match_list)?

**Comment by intinig** [comment]
Hey Jared,

I am currently on holiday without access to my dev laptop. I'll do it in
January. For now in your Gemfile pull directly from Github.

**Comment by jclif** [comment]
Thanks, @intinig. I'll give that a try. 
Also, is there a way to pass options to the match_list_request, e.g. ?rankedQueues=RANKED_SOLO_5x5?
