### ISSUE TITLE
Undefined method `playstyle='

### ISSUE THREAD

**Issue by SantaMinus** [mikamai/ruby-lol#55]
When I do:
**@client.league.get(@player.summoner_id)**,
I get an error:
**NoMethodError: undefined method `playstyle=' for #<Lol::LeagueEntry:0x000000043ee7a8>**.

About a couple of weeks ago it worked fine. 
Could you please help me get it working again?

**Comment by nicolaracco** [comment]
Hi @SantaMinus, I think they added this field during the last weeks. Fixed and released as 0.12.1

**Comment by SantaMinus** [comment]
Thank you so much!
