### ISSUE TITLE
ArgumentError (An hash is required as parameter):

### ISSUE THREAD

**Issue by SantaMinus** [mikamai/ruby-lol#56]
When I call:
**@game_request.spectator_game_info(get_platform(@player.region), @player.summoner_id),**
I get an error: 
**ArgumentError: An hash is required as parameter
from ***/ruby-lol-0.12.1/lib/lol/dynamic_model.rb:11:in `initialize'**

Debugging shows that **hash** variable's class is **HTTParty::Response** in initialize. Should I convert it to a hash somehow?

This problem appeared a day ago, I haven't encountered such error before.
Please help me get rid of it.
Thank you in advance!

**Comment by nicolaracco** [comment]
Hi @SantaMinus
I think we're not handling a fringe case, because when the API responds correctly, I receive the right response. (e.g. platform: 'NA1' and summoner_id: '48010225' is working right now).

Could you detail platform and summoner_id so I can have a look at what this edge case is?

**Comment by SantaMinus** [comment]
Sure. Here is **get_platform** method:

_def get_platform(region)
  platform = region.upcase
  platform << '1' unless region.in? ['kr', 'ru']
  platform
end_

Additionally, here is a screenshot where I get an error even without this method:
![selection_024](https://cloud.githubusercontent.com/assets/3180350/18089602/67eeb0c4-6ec9-11e6-90d7-88fd61a88eb6.png)

**Comment by nicolaracco** [comment]
I think I found and fixed the issue. Can you try to target the github repo directly (see this for info: http://bundler.io/git.html) to confirm this bug is solved? Then we'll release a new version

**Comment by SantaMinus** [comment]
It works now! Thank you very much!
