### ISSUE TITLE
An hash is required as parameter for spectator_game_info

### ISSUE THREAD

**Issue by rhuberdeau** [mikamai/ruby-lol#59]
Each time I try to use the spectator_game_info method in CurrentGameRequest I get an error 'An hash is required as parameter for spectator_game_info'.

Steps to replicate:
    client = Lol::Client.new ENV.fetch("RIOT_API_KEY"), region: 'na'
    current_game_requests = client.current_game
    current_game_requests.spectator_game_info 'NA1', '52372786'

**Comment by rhuberdeau** [comment]
Odd enough I forked this repo, installed from my fork and it works perfectly.

**Comment by nicolaracco** [comment]
Hi @rhuberdeau, this is because we fixed the error on the master branch but we didn't release a new version of the gem 'cause we wanted to complete a refactoring on how requests are done. We should be able to release a new version today.
